### ISSUE TITLE
Doesn't allow for top level meta keys

### ISSUE THREAD

**Issue by sepowitz** [ef4/ember-resource-metadata#6]
Thanks so much for this lib @ef4 ! Saved us a bunch of time, and really like the separation of model & metadata.

We noticed the lib doesn't account for top level keys (which are OK by the jsonapi spec: http://jsonapi.org/format/#document-meta). Totally understand why you'd not want to include this, as there's no guarantee it's actually related to the resource itself.

Our use case - creating & updating "issues" may change the order of an entire set.

As such, our payload looks like this:
```
{
  data: { ... an issue },
  meta: {
    open_issues_sort_orders: [... new issue positions]
  }
```

For now we've extended this lib as such:
```
import DS from 'ember-data';
import AdapterMixin from 'ember-resource-metadata/adapter-mixin';

export default DS.JSONAPIAdapter.extend(AdapterMixin, {
  namespace: 'api',

  // Modified from https://github.com/ef4/ember-resource-metadata/blob/master/addon/adapter-mixin.js
  _correlateMetadata(record, fn) {
    return fn().then(response => {
      const documentMeta = response.meta;

      if (Array.isArray(response.data)) {
        response.data.forEach(hash => {          
          this._correlateResource(
            record, 
            this._decorateHashWithDocumentMeta(hash, documentMeta)
          );
        });
      } else {
        this._correlateResource(
          record, 
          this._decorateHashWithDocumentMeta(response.data, documentMeta)
        );
      }
      return response;
    });
  },

  _decorateHashWithDocumentMeta(hash, documentMeta) {
    if (!documentMeta) return hash;

    if (hash.meta) {
      hash.meta._documentMeta = documentMeta;
    } else {
      hash.meta = { _documentMeta: documentMeta };
    }
    return hash;
  }
});
```

Is this something you'd be open to including (or have a better solution for?)

Thank you!

**Comment by sepowitz** [comment]
cc @hhff

**Comment by ef4** [comment]
ember-data has some support for top-level meta. For example, the record array that comes back from `store.query` or a `hasMany` relationship will have a `meta` property on it if one is available in the response. The feature interacts badly with caching though, so it's not something that works reliably with findRecord or findAll, AFAIK.

The biggest issue I see is what you alluded to -- it's not obvious how to properly correlate document metadata with any particular model. If you load some models via a query or findAll, they will get some collection-level metadata associated with them, but then if you subsequently patch one of the models, or refresh it by itself, that model will get new metadata which is likely to look quite different. This can easily lead to hard-to-understand bugs.

This addon is a hack until somebody can invest the effort into building a proper solution into ember-data, and I'm OK with it because at least the resource-level metadata has a pretty clear meaning that is specific to each model. I don't think we can easily extend it to cover document-level metadata.

When you have app-specific requirements like your `open_issues_sort_orders`, it's probably cleanest to just extend an Adapter directly and handle that value there.

**Comment by hhff** [comment]
Thanks @ef4 - extending the adapter and handling it there is actually a lot neater than our hack above.

Thanks! This is good to close 👍
